server.port=${SERVER_PORT:9090}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/nexusflow_oficial}

jwt.secret=${JWT_SECRET:cambia-esto-en-produccion-minimo-32-chars}
jwt.expiration=36000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

storage.location=${STORAGE_LOCATION:/app/evidencias}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.web=info
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

fastapi.url=${FASTAPI_URL:http://localhost:8000}
fastapi.timeout=30000

ALLOWED_ORIGINS=${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000}
